import {renderTrackFailure} from './failures.js';
import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {renderOverview,renderCaseSummary,cardMarkup, renderBriefing} from './summary.js';

const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kindNames={physics:'物理计算轨迹',reduced_physics:'作者简化动力学',authored_animation:'预设动画 · 不是物理验证',static:'静态模型'};
const poseCache=new Map(), glbCache=new Map();
let data,activeCase,activeTrack,mainViewer,compareViewer,progress=0,playing=false,lastTick=0,group='全部',loadingToken=0;
const loader=new GLTFLoader();
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(`读取失败 (${r.status})：${url}`);return r.json()}
async function poses(url){if(!poseCache.has(url))poseCache.set(url,json(url).then(x=>({...x,frames:x.frames??x.samples??x.replay?.branches?.physical?.frames??[]})));return poseCache.get(url)}
async function glb(url){if(!glbCache.has(url))glbCache.set(url,loader.loadAsync(url));return glbCache.get(url)}
function fmt(t){if(Math.abs(t)<.01)return Number(t).toFixed(6);if(Math.abs(t)<1)return Number(t).toFixed(4);return Number(t).toFixed(3)}
function frameIndex(frames,t){let lo=0,hi=frames.length-1;while(lo<hi){let m=Math.ceil((lo+hi)/2);if(frames[m].time_s<=t+1e-10)lo=m;else hi=m-1}return lo}
function bodyPose(x){return x?.body_poses??x?.poses??{}}
function vec(p){return p.position_abs_m??p.position??[0,0,0]}
function quat(p){const q=p.rotation_abs_quat_wxyz??p.rotation??[1,0,0,0];return new THREE.Quaternion(q[1],q[2],q[3],q[0]).normalize()}

class MotionViewer{
 constructor(id){this.el=$(id);this.canvas=this.el.querySelector('canvas');this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#f5f8fa');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.camera=new THREE.PerspectiveCamera(35,1,.001,1000);this.camera.up.set(0,0,1);this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.addEventListener('change',()=>this.render());this.scene.add(new THREE.HemisphereLight(0xffffff,0x77868d,2.7));for(const [pos,power] of [[[2,-3,5],2.7],[[-3,2,2],1.2]]){const l=new THREE.DirectionalLight(0xffffff,power);l.position.fromArray(pos);this.scene.add(l)}this.bodyNodes=new Map();this.originalMaterials=[];this.frames=[];this.trailGroup=new THREE.Group();this.scene.add(this.trailGroup);new ResizeObserver(()=>this.resize()).observe(this.el);this.resize()}
 resize(){const w=this.el.clientWidth,h=this.el.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.render()}
 async load(c,track){this.el.querySelector('.load-message').hidden=false;this.el.querySelector('.load-message').textContent='正在加载原始模型与保存轨迹…';const geometry=track.geometry??c.geometry;const [g,p]=await Promise.all([glb(geometry),poses(track.poses)]);if(!p.frames.length)throw Error('这条记录没有可播放的姿态');if(this.model){this.scene.remove(this.model);this.model.traverse(n=>{if(n.isMesh){if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material.dispose()}})}this.model=g.scene.clone(true);this.bodyNodes.clear();this.camera.up.fromArray(c.up_axis??[0,0,1]);const ids=new Set(p.frames.flatMap(f=>Object.keys(bodyPose(f))));this.model.traverse(n=>{const id=n.userData.body_id??n.userData.bodyId??n.name;if(ids.has(id)&&!this.bodyNodes.has(id))this.bodyNodes.set(id,n);if(n.isMesh){n.material=Array.isArray(n.material)?n.material.map(m=>m.clone()):n.material.clone();const mats=Array.isArray(n.material)?n.material:[n.material];mats.forEach(m=>{m.userData.baseColor=m.color?.clone();m.userData.baseEmissive=m.emissive?.clone();m.side=THREE.DoubleSide;if(m.metalness!==undefined)m.metalness=.1;if(m.roughness!==undefined)m.roughness=.65})}});this.scene.add(this.model);this.frames=p.frames;this.highlightBodyIds=new Set();this.motionBox=null;this.metadata=p.metadata??{};this.track=track;this.case=c;this.lastIndex=0;this.apply(0);this.fit();this.effects();this.el.querySelector('.load-message').textContent=`原形 ${this.bodyNodes.size} 个仿真刚体 · ${this.frames.length} 个显示帧`;this.binding={pose_body_count:ids.size,matched_body_count:this.bodyNodes.size,unmatched:[...ids].filter(x=>!this.bodyNodes.has(x))};if(this.binding.unmatched.length)this.el.querySelector('.load-message').textContent+=` · ${this.binding.unmatched.length} 项未映射`;this.render();return this.binding}
 apply(fraction){if(!this.frames.length)return;const start=this.frames[0].time_s,end=this.frames.at(-1).time_s;this.currentTime=start+(end-start)*fraction;const i=frameIndex(this.frames,this.currentTime),j=Math.min(i+1,this.frames.length-1);this.lastIndex=i;const a=this.frames[i],b=this.frames[j];const blend=$('smooth').checked&&b.time_s>a.time_s?(this.currentTime-a.time_s)/(b.time_s-a.time_s):0;const ap=bodyPose(a),bp=bodyPose(b);for(const [id,node] of this.bodyNodes){const p=ap[id]??bp[id];if(!p)continue;const q=bp[id]??p;node.position.fromArray(vec(p));if(blend)node.position.lerp(new THREE.Vector3().fromArray(vec(q)),blend);node.quaternion.copy(quat(p));if(blend)node.quaternion.slerp(quat(q),blend)}this.model.updateMatrixWorld(true);if(this.marker&&this.markerBody){const n=this.bodyNodes.get(this.markerBody);if(n)this.marker.position.copy(this.markerLocal).applyMatrix4(n.matrixWorld)}this.render()}
 fit(target=null,mode='iso'){if(!this.model)return;this.model.updateMatrixWorld(true);const box=new THREE.Box3();if(target)box.setFromObject(target);else{for(const [id,node] of this.bodyNodes){if(/^(workbench|ground|table|environment)$/.test(id))continue;box.union(new THREE.Box3().setFromObject(node))}if(box.isEmpty())box.setFromObject(this.model)}if(!target&&this.frames.length>1)box.union(this.motionBounds());if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());this.center=center;this.radius=Math.max(size.length()/2,.015);let direction=new THREE.Vector3(1,-1,.7);if(Math.abs(this.camera.up.y)>.8)direction.set(1,.6,1.7);if(mode==='front')direction=Math.abs(this.camera.up.z)>.8?new THREE.Vector3(0,-1,.18):new THREE.Vector3(0,.15,1);if(mode==='top')direction=this.camera.up.clone().add(new THREE.Vector3(.001,0,0));direction.normalize();const horiz=new THREE.Vector3().crossVectors(this.camera.up,direction).normalize(),vert=new THREE.Vector3().crossVectors(direction,horiz).normalize(),tanY=Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2)),tanX=tanY*this.camera.aspect;let fitted=0;for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const delta=new THREE.Vector3(x,y,z).sub(center);fitted=Math.max(fitted,delta.dot(direction)+Math.max(Math.abs(delta.dot(horiz))/tanX,Math.abs(delta.dot(vert))/tanY))}const dist=Math.max(this.radius*.7,fitted*1.1);this.camera.position.copy(center).addScaledVector(direction,dist);this.camera.near=Math.max(this.radius/1000,.00001);this.camera.far=Math.max(dist*100,10);this.camera.updateProjectionMatrix();this.controls.target.copy(center);this.controls.minDistance=this.radius*.03;this.controls.maxDistance=dist*40;this.controls.update();console.info('FIT_DEBUG '+JSON.stringify({min:box.min.toArray(),max:box.max.toArray(),fitted,dist,position:this.camera.position.toArray(),target:this.controls.target.toArray(),aspect:this.camera.aspect,width:this.el.clientWidth,height:this.el.clientHeight,fov:this.camera.fov}));this.render()}
 motionBounds(){if(this.motionBox)return this.motionBox;const box=new THREE.Box3(),saved=[...this.bodyNodes].map(([id,n])=>[n,n.position.clone(),n.quaternion.clone()]);for(const frame of this.frames){const poses=bodyPose(frame);for(const [id,node] of this.bodyNodes){const p=poses[id];if(p){node.position.fromArray(vec(p));node.quaternion.copy(quat(p))}}this.model.updateMatrixWorld(true);for(const [id,node] of this.bodyNodes){if(!/^(workbench|ground|table|environment)$/.test(id))box.union(new THREE.Box3().setFromObject(node))}}for(const [node,p,q] of saved){node.position.copy(p);node.quaternion.copy(q)}this.model.updateMatrixWorld(true);this.motionBox=box;return box}
 markBodies(ids){this.highlightBodyIds=new Set(ids.map(x=>x.toLowerCase()));this.effects()}
 effects(){if(!this.model)return;this.model.traverse(n=>{if(!n.isMesh)return;let b=n;while(b.parent&&b.parent!==this.model&&!this.bodyNodes.has(b.name))b=b.parent;const name=(b.userData.body_id??b.name??n.name).toLowerCase();const ghost=$('ghost').checked&&/(frame|housing|base|mounting|stand|ground)/.test(name);const mats=Array.isArray(n.material)?n.material:[n.material];mats.forEach(m=>{m.wireframe=$('wire').checked;m.transparent=ghost;m.opacity=ghost?.17:1;m.depthWrite=!ghost;const marked=this.highlightBodyIds?.has(name);if(m.color&&m.userData.baseColor)m.color.copy(marked?new THREE.Color('#db4e35'):m.userData.baseColor);if(m.emissive)m.emissive.copy(marked?new THREE.Color('#641b10'):(m.userData.baseEmissive??new THREE.Color(0)));if(marked){m.opacity=1;m.transparent=false;m.depthWrite=true}})});this.buildTrail();this.render()}
 buildTrail(){this.trailGroup.children.slice().forEach(n=>{this.trailGroup.remove(n);n.geometry?.dispose();n.material?.dispose()});this.marker=null;const id=$('body-select').value,node=this.bodyNodes.get(id);if(!$('trails').checked||!node)return;node.updateWorldMatrix(true,true);const inverse=node.matrixWorld.clone().invert(),local=new THREE.Vector3();let max=-1;node.traverse(n=>{if(!n.isMesh)return;const a=n.geometry.attributes.position,m=inverse.clone().multiply(n.matrixWorld);for(let i=0;i<a.count;i+=Math.max(1,Math.floor(a.count/2500))){const v=new THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(m),r=v.lengthSq();if(r>max){max=r;local.copy(v)}}});const pts=[];for(const f of this.frames){const p=bodyPose(f)[id];if(!p)continue;pts.push(local.clone().applyQuaternion(quat(p)).add(new THREE.Vector3().fromArray(vec(p))))}if(pts.length>1){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xe58a32,transparent:true,opacity:.85}));this.trailGroup.add(line)}this.marker=new THREE.Mesh(new THREE.SphereGeometry(Math.max(this.radius*.012,.0002),12,8),new THREE.MeshBasicMaterial({color:0xe37c20}));this.markerLocal=local;this.markerBody=id;this.trailGroup.add(this.marker);this.marker.position.copy(local).applyMatrix4(node.matrixWorld)}
 render(){if(this.el.clientWidth)this.renderer.render(this.scene,this.camera)}
}

function cards(){const selected=data.cases.filter(c=>group==='全部'||c.group===group);$('cards').innerHTML=selected.map(cardMarkup).join('')}
async function selectTrack(){const token=++loadingToken;pause();progress=0;$('scrub').value=0;activeTrack=activeCase.tracks.find(t=>t.id===$('track-select').value)??activeCase.tracks[0];try{const bind=await mainViewer.load(activeCase,activeTrack);if(token!==loadingToken)return;$('main-kind').textContent=kindNames[activeTrack.type]??activeTrack.type;$('main-track').textContent=activeTrack.title;$('body-select').innerHTML=[...mainViewer.bodyNodes.keys()].map(id=>`<option value="${esc(id)}">${esc(activeTrack.body_labels?.[id]??activeCase.body_labels?.[id]??id)}</option>`).join('');let best=null,score=-1;for(const [id] of mainViewer.bodyNodes){const f=bodyPose(mainViewer.frames[0])[id],l=bodyPose(mainViewer.frames.at(-1))[id];if(!f||!l)continue;let s=new THREE.Vector3().fromArray(vec(f)).distanceTo(new THREE.Vector3().fromArray(vec(l)))+quat(f).angleTo(quat(l))*.05;if(s>score){score=s;best=id}}if(best)$('body-select').value=best;mainViewer.effects();renderTrackFailure(activeCase,activeTrack);$('track-note').textContent=activeTrack.source_note??'';for(const id of ['play','prev','next','last-frame','scrub','speed'])$(id).disabled=activeTrack.type==='static';$('track-meta').textContent=activeTrack.type==='static'?'最终交付的原形静态装配。1 个初始姿态，无运动记录。':`${mainViewer.frames.length} 个显示帧（原 ${activeTrack.metadata?.source_sample_count??mainViewer.frames.length} 个样本） · 已保存 ${fmt(mainViewer.frames[0].time_s)}—${fmt(mainViewer.frames.at(-1).time_s)} 秒\n${activeTrack.complete?'这条请求区间已跑完；结果仍以说明为准。':'仅展示已保存的片段；不是完整功能通过。'}`;$('source-info').textContent=JSON.stringify({track:activeTrack,metadata:mainViewer.metadata,binding:bind},null,2);$('animation-note').textContent=activeCase.tracks.some(t=>t.type==='authored_animation')?'可切换作者预设动画；预设动画不作为物理通过证据。':'没有找到独立保存的预设动画。这里播放已有物理/作者动力学姿态，不补造理想运动。';if($('compare').checked)await loadCompare();update();$('fatal').hidden=true;window.motionApp.ready=true}catch(e){error(e)}}
async function loadCompare(){const track=activeCase.tracks.find(t=>t.id===$('compare-select').value);if(!track)return;if(!compareViewer)compareViewer=new MotionViewer('view-compare');await compareViewer.load(activeCase,track);$('compare-kind').textContent=kindNames[track.type]??track.type;$('compare-track').textContent=track.title;compareViewer.apply(progress);compareViewer.resize()}
function update(){mainViewer?.apply(progress);if($('compare').checked)compareViewer?.apply(progress);if(mainViewer?.frames.length){$('main-time').textContent=`t = ${fmt(mainViewer.currentTime)} s / ${fmt(mainViewer.frames.at(-1).time_s)} s　· 保存帧 ${mainViewer.lastIndex+1}/${mainViewer.frames.length}`;if(compareViewer?.frames.length)$('compare-time').textContent=`t = ${fmt(compareViewer.currentTime)} s / ${fmt(compareViewer.frames.at(-1).time_s)} s　· 保存帧 ${compareViewer.lastIndex+1}/${compareViewer.frames.length}`;const mode=$('smooth').checked?'在相邻保存姿态之间补帧，使播放平滑。':'逐个显示真实保存帧，不在中间补画。';$('play-note').textContent=mode+($('compare').checked?' 两侧同步的是相对进度；各自真实时间显示在画面下方。':' 鼠标拖动旋转，滚轮缩放，右键平移。')+($('trails').checked?' 橙线是所选零件上标记点经过的位置。':'')}$('scrub').value=Math.round(progress*10000)}
function pause(){playing=false;$('play').textContent='▶ 播放';lastTick=0}
function tick(t){if(playing&&mainViewer?.frames.length){const duration=mainViewer.frames.at(-1).time_s-mainViewer.frames[0].time_s;const speed=$('speed').value==='auto'?Math.max(.00005,duration/18):Number($('speed').value);if(lastTick&&duration>0){progress+=Math.min((t-lastTick)/1000,.1)*speed/duration;if(progress>=1){if($('loop').checked)progress%=1;else{progress=1;pause()}}update()}lastTick=t}mainViewer?.controls.update();if($('compare').checked)compareViewer?.controls.update();requestAnimationFrame(tick)}
function error(e){console.error(e);$('fatal').hidden=false;$('fatal').textContent=`这段暂时无法显示：${e.message}`;window.motionApp.error=e.message}
async function openCase(id){activeCase=data.cases.find(c=>c.id===id);if(!activeCase)return;window.motionApp.ready=false;$('catalog').hidden=true;$('detail').hidden=false;$('case-title').textContent=activeCase.title;$('case-summary').textContent=activeCase.summary;$('case-status').textContent=activeCase.status_label;$('case-notes').textContent=Array.isArray(activeCase.notes)?activeCase.notes.join('\n'):activeCase.notes??'';renderCaseSummary(activeCase);$('track-select').innerHTML=activeCase.tracks.map(t=>`<option value="${esc(t.id)}">${esc(t.title)} · ${esc(kindNames[t.type]??t.type)}</option>`).join('');$('compare-select').innerHTML=$('track-select').innerHTML;$('compare-select').selectedIndex=Math.min(1,activeCase.tracks.length-1);if(!mainViewer)mainViewer=new MotionViewer('view-main');await selectTrack();requestAnimationFrame(tick)}
$('track-select').onchange=selectTrack;$('compare-select').onchange=async()=>{pause();await loadCompare();update()};$('compare').onchange=async()=>{$('pane-compare').hidden=!$('compare').checked;$('compare-select-wrap').hidden=!$('compare').checked;$('stage-grid').classList.toggle('dual',$('compare').checked);if($('compare').checked)await loadCompare();mainViewer.resize();update()};$('play').onclick=()=>{playing=!playing;lastTick=0;if(progress>=1)progress=0;$('play').textContent=playing?'❚❚ 暂停':'▶ 播放'};$('scrub').oninput=()=>{pause();progress=Number($('scrub').value)/10000;update()};for(const [id,delta] of [['prev',-1],['next',1]])$(id).onclick=()=>{pause();const frames=mainViewer.frames,i=THREE.MathUtils.clamp(mainViewer.lastIndex+delta,0,frames.length-1),a=frames[0].time_s,b=frames.at(-1).time_s;progress=b>a?(frames[i].time_s-a)/(b-a):0;update()};$('reset').onclick=()=>{mainViewer.fit();compareViewer?.fit()};$('front').onclick=()=>{mainViewer.fit(null,'front');compareViewer?.fit(null,'front')};$('top-view').onclick=()=>{mainViewer.fit(null,'top');compareViewer?.fit(null,'top')};$('focus').onclick=()=>{const id=$('body-select').value;mainViewer.fit(mainViewer.bodyNodes.get(id));compareViewer?.fit(compareViewer.bodyNodes.get(id))};for(const id of ['wire','ghost','trails','body-select'])$(id).onchange=()=>{mainViewer?.effects();compareViewer?.effects();update()};$('smooth').onchange=update;$('last-frame').onclick=()=>{pause();progress=1;update()};

async function locateFailure(target){const trackId=target.dataset.track;if(!activeCase.tracks.some(t=>t.id===trackId))return;if(activeTrack.id!==trackId){$('track-select').value=trackId;await selectTrack()}pause();const time=Number(target.dataset.time),first=mainViewer.frames[0].time_s,last=mainViewer.frames.at(-1).time_s;progress=last>first?Math.max(0,Math.min(1,(time-first)/(last-first))):0;update();const bodies=(target.dataset.bodies??'').split('|').filter(Boolean);mainViewer.markBodies(bodies);mainViewer.fit();$('failure-clear').hidden=!bodies.length;$('view-main').scrollIntoView({behavior:'smooth',block:'center'})}
for(const id of ['failure-panel','detail-tests'])$(id).addEventListener('click',async event=>{const target=event.target.closest('[data-track]');if(target)await locateFailure(target);if(event.target.id==='failure-clear'){mainViewer.markBodies([]);event.target.hidden=true}});
window.motionApp={ready:false,error:null,openCase,selectTrack,setProgress:v=>{pause();progress=v;update()},state:()=>({case:activeCase?.id,track:activeTrack?.id,time:mainViewer?.currentTime,frame:mainViewer?.lastIndex,binding:mainViewer?.binding,bodyMatrices:mainViewer?[...mainViewer.bodyNodes].map(([id,n])=>({id,p:n.position.toArray(),q:n.quaternion.toArray()})):[]}),capture:()=>mainViewer?.canvas.toDataURL('image/png'),viewer:()=>mainViewer};
try{data=await json('gallery.json');window.motionApp.data=data;$('snapshot').textContent=data.snapshot_label??'已有记录的固定截点';const tracks=data.cases.flatMap(c=>c.tracks);renderOverview(data); void renderBriefing();const groups=['全部',...new Set(data.cases.map(c=>c.group))];$('filters').innerHTML=groups.map(g=>`<button ${g==='全部'?'class="active"':''} data-group="${esc(g)}">${esc(g)}</button>`).join('');$('filters').onclick=e=>{if(!e.target.dataset.group)return;group=e.target.dataset.group;for(const b of $('filters').children)b.classList.toggle('active',b.dataset.group===group);cards()};cards();const id=new URLSearchParams(location.search).get('case');if(id)await openCase(id)}catch(e){error(e);$('catalog').insertAdjacentHTML('beforeend',`<p>${esc(e.message)}</p>`)}
